// <auto-generated />
using System;
using DytronCustomers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DytronCustomers.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20241026095047_SeedCustomers")]
    partial class SeedCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DytronCustomers.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5282),
                            Email = "customer1@example.com",
                            FirstName = "First-1",
                            LastName = "Last-1",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5292)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5296),
                            Email = "customer2@example.com",
                            FirstName = "First-2",
                            LastName = "Last-2",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5296)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5298),
                            Email = "customer3@example.com",
                            FirstName = "First-3",
                            LastName = "Last-3",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5298)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5300),
                            Email = "customer4@example.com",
                            FirstName = "First-4",
                            LastName = "Last-4",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5301)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5302),
                            Email = "customer5@example.com",
                            FirstName = "First-5",
                            LastName = "Last-5",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5303)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5304),
                            Email = "customer6@example.com",
                            FirstName = "First-6",
                            LastName = "Last-6",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5305)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5306),
                            Email = "customer7@example.com",
                            FirstName = "First-7",
                            LastName = "Last-7",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5307)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5308),
                            Email = "customer8@example.com",
                            FirstName = "First-8",
                            LastName = "Last-8",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5308)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5310),
                            Email = "customer9@example.com",
                            FirstName = "First-9",
                            LastName = "Last-9",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5310)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5313),
                            Email = "customer10@example.com",
                            FirstName = "First-10",
                            LastName = "Last-10",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5313)
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5315),
                            Email = "customer11@example.com",
                            FirstName = "First-11",
                            LastName = "Last-11",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5315)
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5317),
                            Email = "customer12@example.com",
                            FirstName = "First-12",
                            LastName = "Last-12",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5318)
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5319),
                            Email = "customer13@example.com",
                            FirstName = "First-13",
                            LastName = "Last-13",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5319)
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5321),
                            Email = "customer14@example.com",
                            FirstName = "First-14",
                            LastName = "Last-14",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5321)
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5322),
                            Email = "customer15@example.com",
                            FirstName = "First-15",
                            LastName = "Last-15",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5322)
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5324),
                            Email = "customer16@example.com",
                            FirstName = "First-16",
                            LastName = "Last-16",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5324)
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5325),
                            Email = "customer17@example.com",
                            FirstName = "First-17",
                            LastName = "Last-17",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5326)
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5327),
                            Email = "customer18@example.com",
                            FirstName = "First-18",
                            LastName = "Last-18",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5328)
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5329),
                            Email = "customer19@example.com",
                            FirstName = "First-19",
                            LastName = "Last-19",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5329)
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5330),
                            Email = "customer20@example.com",
                            FirstName = "First-20",
                            LastName = "Last-20",
                            LastUpdatedDate = new DateTime(2024, 10, 26, 3, 50, 46, 840, DateTimeKind.Local).AddTicks(5331)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
